# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df557403a18c8c46f6ba2ee747aac75f1c35db44fc5f130d1993ab003be31bfb912c9538e4fe5d238d1505510de7625f38d9e28241f7eed46323f9f3aaceac27

test:
  secret_key_base: 874eddfa5bdcca6a5bd81a742f22ee76481fd7f8befc630b2a6d06f9b9b0462b900ed5b777a6e902b437909a1e29a4fcd509c86fc58c0c92511a9d347c8bae94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
